### ISSUE TITLE
NoSuchFieldError on SignChangeEvent

### ISSUE THREAD

**Issue by karu724** [NyaaCat/LockettePro#27]
[22:06:34] [Server thread/ERROR]: Could not pass event SignChangeEvent to LockettePro v2.15
java.lang.NoSuchFieldError: Class org.bukkit.Particle does not have member field 'org.bukkit.Particle SMOKE'
	at me.crafter.mc.lockettepro.BlockPlayerListener.onAttemptChangeLockerSign(BlockPlayerListener.java:245) ~[LockettePro-2.15.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor711.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[plazma-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[plazma-api-1.20.4-R0.1-SNAPSHOT.jar:git-Plazma-"3972882"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[plazma-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:62) ~[plazma-1.20.4.jar:git-Plazma-"3972882"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[plazma-1.20.4.jar:git-Plazma-"3972882"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[plazma-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.entity.SignBlockEntity.setMessages(SignBlockEntity.java:240) ~[?:?]
	at net.minecraft.world.level.block.entity.SignBlockEntity.lambda$updateSignText$4(SignBlockEntity.java:186) ~[?:?]
	at net.minecraft.world.level.block.entity.SignBlockEntity.updateText(SignBlockEntity.java:200) ~[?:?]
	at net.minecraft.world.level.block.entity.SignBlockEntity.updateSignText(SignBlockEntity.java:185) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.updateSignText(ServerGamePacketListenerImpl.java:3480) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleSignUpdate$20(ServerGamePacketListenerImpl.java:3461) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[plazma-1.20.4.jar:git-Plazma-"3972882"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1510) ~[plazma-1.20.4.jar:git-Plazma-"3972882"]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[plazma-1.20.4.jar:git-Plazma-"3972882"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1487) ~[plazma-1.20.4.jar:git-Plazma-"3972882"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1401) ~[plazma-1.20.4.jar:git-Plazma-"3972882"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1379) ~[plazma-1.20.4.jar:git-Plazma-"3972882"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[plazma-1.20.4.jar:git-Plazma-"3972882"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[plazma-1.20.4.jar:git-Plazma-"3972882"]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by Lori3f6** [comment]
Should fixed since this [build](https://ci.nyaacat.com/job/LockettePro/job/main/9/) for https://github.com/NyaaCat/LockettePro/commit/3a69f0398ed60e71af0d3ad10874d9cf709c8c6d

**Comment by karu724** [comment]
thank you :)
